### ISSUE TITLE
Fixing jackmaster 0.0.2

### ISSUE THREAD

**Issue by jpcima** [ycollet/jackmaster#1]
Hi @ycollet, I already fixed jackmaster for GTK2, and I placed a repository at https://github.com/linuxmao-org/jackmaster.
Lets' not duplicate our work. :+1: 

I would like in the future to have it work in GTK3, to ensure the software perennity for a bit longer.
It still uses a good number of GTK2 obsolete API at the moment.

**Comment by ycollet** [comment]
OK, I will close this repo.
Thanks for the link.

**Comment by jpcima** [comment]
ok @ycollet, I can grant write privileges on the linuxmao repo, do you want to have them?

**Comment by ycollet** [comment]
I will first work on the linuxmao repo via pull request. Just for the 
code review.

And once you will be satisfied by my way of coding, I will ask for this 
privileges :)

Thanks a lot !

Le 17/08/2019 à 17:23, JP Cimalando a écrit :

**Comment by jpcima** [comment]
No problem :+1: 
Feel free to close this repo if you want
